sudo: false
language: node_js
node_js:
  - '0.12'
  - '6.5.0'
env:
  global:
    # Please get your own free key if you want to test yourself
    - SAUCE_USERNAME=dojo2-ts-ci
    - SAUCE_ACCESS_KEY=e92610e3-834e-4bec-a3b5-6f7b9d874601
  matrix:
    - INTERN_NODE_ONLY=1
    - INTERN_NODE_ONLY=0
matrix:
  exclude:
    - node_js: '0.12'
      env: INTERN_NODE_ONLY=0
    - node_js: '6.5.0'
      env: INTERN_NODE_ONLY=1
cache:
  directories:
    - node_modules
script: tests/selftest.sh
notifications:
  slack:
    secure: RvW7LoV4mBzNz481eqfhLB/QNuJYht9Fpz7F+vtVjD/RacDJfc7397/8pJcl2yP+Ft2X7yJsM6bx3Uq22CfMiZ7HTVOfb+tYQNBQ5vcluUvd3fYV72M4oWe/TTFTlAulC04vWs4/QRHqbvmsXXr8Rn8Jj2LjsxnKvP0UNr0aLxk=
