language: node_js
node_js:
  - 0.10
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME: dojo2-ts-ci
    - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
install:
  travis_retry npm install
  cd node_modules/intern
  # Patches for CommonJS code coverage; remove when updating to use Intern 2
  curl https://github.com/theintern/intern/commit/6f418cdad8e004faa18cf26420bf23134a8c22a2.patch |patch -p1
  curl https://github.com/theintern/intern/commit/d5f69ca860302c8fa24d7af97fca1e5e5c2b4c3f.patch |patch -p1
  cd ../..
script: tests/run.sh
